// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd0M3CEtV-30is4l8_5hkNT7i9Gc-oR9w',
    appId: '1:236120652032:web:6501c063e17b7d2b495be5',
    messagingSenderId: '236120652032',
    projectId: 'ensetracker',
    authDomain: 'ensetracker.firebaseapp.com',
    storageBucket: 'ensetracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV7Bl9KLB-m0BbWoHNCOU0KsecUuQAN2Q',
    appId: '1:236120652032:android:83ba01efef582d80495be5',
    messagingSenderId: '236120652032',
    projectId: 'ensetracker',
    storageBucket: 'ensetracker.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd0M3CEtV-30is4l8_5hkNT7i9Gc-oR9w',
    appId: '1:236120652032:web:13ecd4469b8675a5495be5',
    messagingSenderId: '236120652032',
    projectId: 'ensetracker',
    authDomain: 'ensetracker.firebaseapp.com',
    storageBucket: 'ensetracker.firebasestorage.app',
  );

}