// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSnNvwE4cVIDk2ztLu0-NGOWN0xboMN-k',
    appId: '1:861197441104:android:7658094145d3a3832c1955',
    messagingSenderId: '861197441104',
    projectId: 'meals-e69bb',
    storageBucket: 'meals-e69bb.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU0rmb7vRbmbcjpCIoZKJ58nmv-6Jdee4',
    appId: '1:266368257016:web:4c403b838fccb44046640d',
    messagingSenderId: '266368257016',
    projectId: 'vpnbackend',
    authDomain: 'vpnbackend.firebaseapp.com',
    databaseURL: 'https://vpnbackend-default-rtdb.firebaseio.com',
    storageBucket: 'vpnbackend.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4RoQ6F4tMketh0YeeZzEpTaN8Frg1g9A',
    appId: '1:861197441104:web:0683c5c9affdbfb62c1955',
    messagingSenderId: '861197441104',
    projectId: 'meals-e69bb',
    authDomain: 'meals-e69bb.firebaseapp.com',
    storageBucket: 'meals-e69bb.firebasestorage.app',
  );

}